version: "3.1"
secrets:
  secrets.env:
    file: ./config/secrets.env

services:
  api:
    build: .
    image: mirrorx_node
    command: node --experimental-modules api.mjs
    environment:
      API_PORT: 80
    ports:
      - "80:80"
    secrets:
      - secrets.env
  match:
    build: .
    image: mirrorx_node
    command: node --experimental-modules match.mjs 0.01 ETH
    secrets:
      - secrets.env