version: "3.1"
secrets:
  secrets.env:
    file: ./config/secrets.env

services:
  api:
    build: .
    image: mirrorx_node
    command: node --experimental-modules api.mjs
    environment:
      API_PORT: 80
      REDIS_URI: redis://redis
    ports:
    - "9080:80"
    secrets:
    - secrets.env
    links:
    - redis
  match:
    build: .
    image: mirrorx_node
    command: node --experimental-modules match.mjs
    environment:
      REDIS_URI: redis://redis
    secrets:
    - secrets.env
    links:
    - redis
  redis:
    image: redis:4.0.8
    ports:
    - "6379:6379"
